Re-incorporate concurrent changes made to pipeline

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -7,6 +7,9 @@ permissions:
 
 on:
   push:
+    branches: [main]
+  pull_request:
+    branches: [main]
 
 jobs:
   lint:
@@ -29,7 +32,7 @@ jobs:
         run: dotnet format --include DfE.GIAP.Core/ DfE.GIAP.Core.UnitTests/ --verify-no-changes
         working-directory: ${{ env.SOLUTION_DIRECTORY }}
 
-  build_and_test:
+  build_test_package:
     runs-on: ubuntu-latest
 
     env:
@@ -39,39 +42,26 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
+      - name: Build
+        uses: ./.github/actions/build
         with:
-          node-version: '12'
-
-      - name: Setup .NET SDK from global.json
-        uses: actions/setup-dotnet@v4
-
-      - name: Install NuGet
-        uses: NuGet/setup-nuget@v1
-
-      - name: npm install
-        run: npm install
-        working-directory: ${{ env.SOLUTION_DIRECTORY }}/DfE.GIAP.Web
-
-      - name: Add DfEDigital NuGet Feed
-        run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name dfedigital "https://nuget.pkg.github.com/DFE-Digital/index.json"
-
-      - name: Restore NuGet packages
-        run: dotnet restore *.sln
-        working-directory: ${{ env.SOLUTION_DIRECTORY }}
-
-      - name: Build solution
-        run: dotnet build *.sln --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore -p:SkipInvalidConfigurations=true
-
-        # These are specific to windows-latest msdeploy so have been removed temporarily
-        #-p:DesktopBuildPackageLocation="${{ github.workspace }}\WebApp.zip"
-        # -p:DeployOnBuild=true -p:WebPublishMethod=Package -p:PackageAsSingleFile=true -p:DeployIisAppPath="Default Web Site"
-        working-directory: ${{ env.SOLUTION_DIRECTORY }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Run unit tests
-        run: dotnet test *.sln --configuration ${{ env.BUILD_CONFIGURATION }} --collect "XPlat Code coverage" -- RunConfiguration.DisableAppDomain=true
+        run: |
+          for proj in \
+            ./DfE.GIAP.Common.Tests/DfE.GIAP.Common.Tests.csproj \
+            ./DfE.GIAP.Service.Tests/DfE.GIAP.Service.Tests.csproj \
+            ./DfE.GIAP.Web.Tests/DfE.GIAP.Web.Tests.csproj \
+            ./DfE.GIAP.Core.UnitTests/DfE.GIAP.Core.UnitTests.csproj
+          do
+            echo "Running tests for $proj"
+            dotnet test "$proj" \
+              --verbosity normal \
+              --collect:"XPlat Code Coverage" \
+              -p:CoverletOutputFormat=cobertura \
+              -p:CoverletOutput=./TestResults/
+          done
         working-directory: ${{ env.SOLUTION_DIRECTORY }}
 
       - name: Install ReportGenerator tool
@@ -87,6 +77,19 @@ jobs:
         with:
           name: coverage-report
           path: ${{ env.SOLUTION_DIRECTORY }}/coverlet/reports/Cobertura.xml
+
+      - name: Summarise code coverage
+        uses: irongut/CodeCoverageSummary@v1.3.0
+        with:
+          filename: ${{ env.SOLUTION_DIRECTORY }}/coverlet/reports/Cobertura.xml
+          badge: true
+          fail_below_min: true
+          format: markdown
+          hide_branch_rate: false
+          hide_complexity: true
+          indicators: true
+          output: both
+          thresholds: '60 80'
 
       - name: Run gulp
         run: |
@@ -108,107 +111,172 @@ jobs:
           path: publish
           if-no-files-found: error
 
-  deploy_dev:
+  local_integration_tests:
+    runs-on: ubuntu-latest
+    needs: build_test_package
+    services:
+      cosmosdb:
+        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
+        ports:
+          - 8081:8081
+          - 10250-10255:10250-10255
+        env:
+          AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 5
+          AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build
+        uses: ./.github/actions/build
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install CosmosDb Emulator TLS certificate
+        run: |
+          retry_count=0
+          max_retry_count=10
+          until sudo curl --insecure --silent --fail --show-error "https://localhost:8081/_explorer/emulator.pem" --output "/usr/local/share/ca-certificates/cosmos-db-emulator.crt"; do
+            if [ $retry_count -eq $max_retry_count ]; then
+              echo "Failed to download certificate after $retry_count attempts."
+              exit 1
+            fi
+            echo "Failed to download certificate. Retrying in 5 seconds..."
+            sleep 5
+            retry_count=$((retry_count+1))
+          done
+          sudo update-ca-certificates
+
+      - name: Run Integration Tests
+        run: dotnet test ./DfE.GIAP.All/DfE.GIAP.Core.IntegrationTests/DfE.GIAP.Core.IntegrationTests.csproj --no-build --verbosity normal
+
+  deploy_dev_poc:
     uses: ./.github/workflows/deploy.yml
-    needs: [build_and_test, lint]
+    needs: [build_test_package, lint, local_integration_tests]
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     with:
       environment: development
+      ## Temporary POC on Azure
       app_name: giap-deploy-demo-development
     secrets:
       AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
       AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
       AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
-  smoke_test_dev:
+  smoke_test_dev_poc:
     uses: ./.github/workflows/smoke-test.yml
-    needs: deploy_dev
+    needs: deploy_dev_poc
     if: github.event_name == 'push' && github.ref == 'refs/heads/main'
     with:
-      environment: development
-      app_url: ${{ needs.deploy_dev.outputs.app_url }}
+      environment: development-poc
+      app_url: ${{ needs.deploy_dev_poc.outputs.app_url }}
 
-  deploy_test:
-    uses: ./.github/workflows/deploy.yml
-    needs: smoke_test_dev
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    with:
-      environment: test
-      app_name: giap-deploy-demo-test
-    secrets:
-      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-  smoke_test_test:
-    uses: ./.github/workflows/smoke-test.yml
-    needs: deploy_test
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    with:
-      environment: test
-      app_url: ${{ needs.deploy_test.outputs.app_url }}
-
-##  PLACEHOLDERS FOR ADDITIONAL TESTS
-#  integration_test_test:
-#    uses: ./.github/workflows/integration-test.yml
-#    needs: smoke_test_dev
+#  deploy_dev:
+#    uses: ./.github/workflows/deploy.yml
+#    needs: [build_test_package, lint, local_integration_tests]
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 #    with:
-#      environment: test
+#      environment: development
+#      ## Temporary POC on CIP
+#      app_name: s115d10-s115d10-as-searchweb-cs-gha-poc
+#    secrets:
+#      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#
+#  smoke_test_dev:
+#    uses: ./.github/workflows/smoke-test.yml
+#    needs: deploy_dev
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    with:
+#      environment: development
 #      app_url: ${{ needs.deploy_dev.outputs.app_url }}
 #
-#  accessibilty_test_test:
-#    uses: ./.github/workflows/accessibility-test.yml
+#  deploy_test:
+#    uses: ./.github/workflows/deploy.yml
 #    needs: smoke_test_dev
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 #    with:
 #      environment: test
-#      app_url: ${{ needs.deploy_dev.outputs.app_url }}
+#      app_name: giap-deploy-demo-test
+#    secrets:
+#      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 #
-  deploy_preproduction:
-    uses: ./.github/workflows/deploy.yml
-#    needs: [smoke_test_test, integration_test_test, accessibilty_test_test]
-    needs: [smoke_test_test]
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    with:
-      environment: preproduction
-      app_name: giap-deploy-demo-preproduction
-    secrets:
-      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-  smoke_test_preproduction:
-    uses: ./.github/workflows/smoke-test.yml
-    needs: deploy_preproduction
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    with:
-      environment: preproduction
-      app_url: ${{ needs.deploy_preproduction.outputs.app_url }}
-
-##  PLACEHOLDERS FOR ADDITIONAL TESTS
-#  performance_test_preproduction:
-#    uses: ./.github/workflows/performance-test.yml
-#    needs: smoke_test_dev
+#  smoke_test_test:
+#    uses: ./.github/workflows/smoke-test.yml
+#    needs: deploy_test
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    with:
+#      environment: test
+#      app_url: ${{ needs.deploy_test.outputs.app_url }}
+#
+###  PLACEHOLDERS FOR ADDITIONAL TESTS
+##  integration_test_test:
+##    uses: ./.github/workflows/integration-test.yml
+##    needs: smoke_test_dev
+##    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+##    with:
+##      environment: test
+##      app_url: ${{ needs.deploy_dev.outputs.app_url }}
+##
+##  accessibilty_test_test:
+##    uses: ./.github/workflows/accessibility-test.yml
+##    needs: smoke_test_dev
+##    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+##    with:
+##      environment: test
+##      app_url: ${{ needs.deploy_dev.outputs.app_url }}
+##
+#  deploy_preproduction:
+#    uses: ./.github/workflows/deploy.yml
+##    needs: [smoke_test_test, integration_test_test, accessibilty_test_test]
+#    needs: [smoke_test_test]
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 #    with:
 #      environment: preproduction
-#      app_url: ${{ needs.deploy_dev.outputs.app_url }}
-
-  deploy_prod:
-    uses: ./.github/workflows/deploy.yml
-    needs: smoke_test_preproduction
-#    needs: [smoke_test_preproduction, performance_test_preproduction]
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    with:
-      environment: production
-      app_name: giap-deploy-demo-production
-    secrets:
-      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-  smoke_test_prod:
-    uses: ./.github/workflows/smoke-test.yml
-    needs: deploy_prod
-    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-    with:
-      environment: production
-      app_url: ${{ needs.deploy_prod.outputs.app_url }}
+#      app_name: giap-deploy-demo-preproduction
+#    secrets:
+#      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#
+#  smoke_test_preproduction:
+#    uses: ./.github/workflows/smoke-test.yml
+#    needs: deploy_preproduction
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    with:
+#      environment: preproduction
+#      app_url: ${{ needs.deploy_preproduction.outputs.app_url }}
+#
+###  PLACEHOLDERS FOR ADDITIONAL TESTS
+##  performance_test_preproduction:
+##    uses: ./.github/workflows/performance-test.yml
+##    needs: smoke_test_dev
+##    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+##    with:
+##      environment: preproduction
+##      app_url: ${{ needs.deploy_dev.outputs.app_url }}
+#
+#  deploy_prod:
+#    uses: ./.github/workflows/deploy.yml
+#    needs: smoke_test_preproduction
+##    needs: [smoke_test_preproduction, performance_test_preproduction]
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    with:
+#      environment: production
+#      app_name: giap-deploy-demo-production
+#    secrets:
+#      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+#      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+#      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+#
+#  smoke_test_prod:
+#    uses: ./.github/workflows/smoke-test.yml
+#    needs: deploy_prod
+#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+#    with:
+#      environment: production
+#      app_url: ${{ needs.deploy_prod.outputs.app_url }}
